In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier as DT

In [3]:
df=pd.read_csv("/content/drive/MyDrive/ExcelR/Assignment/Random Rorests/Company_Data.csv")

In [4]:
df.head()

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
3,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes
4,4.15,141,64,3,340,128,Bad,38,13,Yes,No

In [5]:
df.describe()

,Sales,CompPrice,Income,Advertising,Population,Price,Age,Education
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,7.496325,124.975000,68.657500,6.635000,264.840000,115.795000,53.322500,13.900000
std,2.824115,15.334512,27.986037,6.650364,147.376436,23.676664,16.200297,2.620528
min,0.000000,77.000000,21.000000,0.000000,10.000000,24.000000,25.000000,10.000000
25%,5.390000,115.000000,42.750000,0.000000,139.000000,100.000000,39.750000,12.000000
50%,7.490000,125.000000,69.000000,5.000000,272.000000,117.000000,54.500000,14.000000
75%,9.320000,135.000000,91.000000,12.000000,398.500000,131.000000,66.000000,16.000000
max,16.270000,175.000000,120.000000,29.000000,509.000000,191.000000,80.000000,18.000000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64
 2   Income       400 non-null    int64
 3   Advertising  400 non-null    int64
 4   Population   400 non-null    int64
 5   Price        400 non-null    int64
 6   ShelveLoc    400 non-null    object
 7   Age          400 non-null    int64
 8   Education    400 non-null    int64
 9   Urban        400 non-null    object
 10  US           400 non-null    object
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB

In [7]:
df["Sales"]

0       9.50
1      11.22
2      10.06
3       7.40
4       4.15
       ...
395    12.57
396     6.14
397     7.41
398     5.94
399     9.71
Name: Sales, Length: 400, dtype: float64

In [8]:
np.median(df['Sales'])
df["sales"]="<=7.49"
df.loc[df["Sales"]>=7.49,"sales"]=">=7.49"

In [9]:
df["sales"].unique()

array(['>=7.49', '<=7.49'], dtype=object)

In [10]:
df.drop(["Sales"],axis=1,inplace=True)

In [11]:
df.isnull().sum()

CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
sales          0
dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   CompPrice    400 non-null    int64
 1   Income       400 non-null    int64
 2   Advertising  400 non-null    int64
 3   Population   400 non-null    int64
 4   Price        400 non-null    int64
 5   ShelveLoc    400 non-null    object
 6   Age          400 non-null    int64
 7   Education    400 non-null    int64
 8   Urban        400 non-null    object
 9   US           400 non-null    object
 10  sales        400 non-null    object
dtypes: int64(7), object(4)
memory usage: 34.5+ KB

In [13]:
le=preprocessing.LabelEncoder()

In [14]:
for column_name in df.columns:
    if df[column_name].dtype==object:
        df[column_name]=le.fit_transform(df[column_name])
    else:
      pass

In [15]:
features=df.iloc[:,0:10]
labels=df.iloc[:,10]

In [16]:
X_train,X_test,Y_train,Y_test=train_test_split(features,labels,test_size=0.3,stratify=labels)

In [17]:
Y_train.value_counts()

1    141
0    139
Name: sales, dtype: int64

In [18]:
Y_test.value_counts()

1    60
0    60
Name: sales, dtype: int64

# **Building the Model**

In [19]:
model=DT(criterion="entropy")
model.fit(X_train,Y_train)

DecisionTreeClassifier(criterion='entropy')

In [20]:
pred_train=pd.DataFrame(model.predict(X_train))
pred_train

     0
0    0
1    1
2    1
3    0
4    1
..  ..
275  1
276  1
277  0
278  0
279  0

[280 rows x 1 columns]

In [21]:
acc_train=accuracy_score(Y_train,pred_train)
acc_train

1.0

In [22]:
pred_test=pd.DataFrame(model.predict(X_test))
pred_test

     0
0    1
1    0
2    0
3    0
4    1
..  ..
115  1
116  1
117  0
118  0
119  1

[120 rows x 1 columns]

In [24]:
acc_test=accuracy_score(Y_test,pred_test)
acc_test

0.75

In [25]:
confusion_test=pd.DataFrame(confusion_matrix(Y_test,pred_test))
confusion_test

    0   1
0  48  12
1  18  42